name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend Docker image
        run: |
          docker build -f frontend/Dockerfile -t frontend:latest frontend

      - name: Build Backend Docker image
        run: |
          docker build -f backend/Dockerfile -t backend:latest backend
